### ISSUE TITLE
[Pro Evolution Soccer 2013] Menu SFX distorted/loops, but background music is fine

### ISSUE THREAD

**Issue by guihkx** [zfigura/wine#16] opened 2018-09-05 10:02 UTC
I've been testing some games with Proton 3.7-5 Beta (all of them with esync enabled), and so far this is the only game I've experienced this audio issue. If esync is enabled, the menu sound effects get really distorted and they kind of play in an infinite loop, but the background music plays just fine. That does not happen when esync is disabled.

I've recorded two short videos of me launching the game with esync on and off (the logs I'm attaching were also generated during the recording of the videos). The debug flags I used: `+esync,+server,+pid,+timestamp,+seh,+xaudio2`

* Pro Evolution Soccer 2013 (+ESYNC)
Log file: [steam-221430+esync.tar.gz](https://github.com/zfigura/wine/files/2352260/steam-221430%2Besync.tar.gz)
Demo video: https://www.youtube.com/watch?v=6jbYjN1WQmo

* Pro Evolution Soccer 2013 (NO ESYNC)
Log file: [steam-221430+noesync.tar.gz](https://github.com/zfigura/wine/files/2352263/steam-221430%2Bnoesync.tar.gz)
Demo video: https://www.youtube.com/watch?v=kHeTgmYm75U

Let me know if you need anything else.
Thank you

**Comment by zfigura** [comment] 2018-09-05 15:24
Looks like another game that relies on PulseEvent(), marking as duplicate of #10 for now.

**Closed as completed by zfigura** 2018-09-05 15:24 UTC
Labels: duplicate
