### ISSUE TITLE
Clipboard not working correctly

### ISSUE THREAD

**Issue by potatoattack** [zfigura/wine#9] opened 2018-08-13 01:00 UTC
Copy and pasting from a wine program into a non-wine program does not work. Though it works the other way around.
With a clean wine prefix I run:
```
wine notepad
```
then open a native text editor (e.g., kate) and copy and paste text back and forth between them. Sometimes it takes a few copies before it fails.
This happens with esync enabled and disabled.
Please let me know if any logs would be useful.

**Comment by zfigura** [comment] 2018-08-13 04:25
I can't seem to easily reproduce this. If you can reproduce this with a +server,+clipboard,+hook log, can you please attach one?

**Comment by potatoattack** [comment] 2018-08-13 05:28
Sure, here is a log with it happening a few times.
[wine.log.gz](https://github.com/zfigura/wine/files/2281822/wine.log.gz)
made with: 
`WINEDEBUG=+server,+clipboard,+hook notepad > wine.log 2>&1`

**Comment by zfigura** [comment] 2018-08-14 02:41
Thanks. I'm not sure why I couldn't reproduce the bug on my machine, but the cause was clear enough. Can you test with the latest master? If necessary I can provide a tarball of the patches.

**Comment by potatoattack** [comment] 2018-08-14 22:24
Yep this has fixed the issue =D

**Comment by zfigura** [comment] 2018-08-14 22:51
Thanks; closing then.

**Closed as completed by zfigura** 2018-08-14 22:51 UTC
