### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tysegall** [zfigura/wine#8] opened 2018-08-12 06:55 UTC
This is on Debian sid with gcc/g++ 8.2.0.  Looking to use your esync variant for Witcher 3.  Anyway, here's the configure details and the last bit of output that shows the error.  Using the latest on the esync branch.

```
./configure --prefix=/opt/wine3-esync --enable-win64

make[1]: Leaving directory '/home/wls/git/wine-witcher-esync/dlls/npptools'
make[1]: Entering directory '/home/wls/git/wine-witcher-esync/dlls/ntdll'
gcc -m64 -c -o esync.o esync.c -I. -I../../include -D__WINESRC__ -D_NTSYSTEM_ -D_REENTRANT -fPIC -Wall \
  -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 \
  -gstrict-dwarf -g -O2
esync.c:322:17: error: conflicting types for ‘create_esync’
 static NTSTATUS create_esync( enum esync_type type, HANDLE *handle,
                 ^~~~~~~~~~~~
esync.c:111:17: note: previous declaration of ‘create_esync’ was here
 static NTSTATUS create_esync( enum esync_type type, HANDLE *handle,
                 ^~~~~~~~~~~~
esync.c:111:17: warning: ‘create_esync’ used but never defined
make[1]: *** [Makefile:343: esync.o] Error 1
make[1]: Leaving directory '/home/wls/git/wine-witcher-esync/dlls/ntdll'
make: *** [Makefile:9367: dlls/ntdll] Error 2

```

**Comment by Tk-Glitch** [comment] 2018-08-12 11:14
I can confirm the issue. I have also received a report about it from another user.

**Comment by gonX** [comment] 2018-08-12 12:06
I have been running into the same issue when trying to include wine-staging and wine 3.13. I can provide an Arch Linux PKGBUILD and final wine-staging patch (inspired by @Tk-Glitch's patch but rewritten for 04b738c8) to prepare for the esync patches.

I am not getting this issue compiling from the `esync` branch, so I think the problem is in `esync.tgz` packaging, or an oversight in the intermediate patch that occured for both me and Tk-Glitch.

**Comment by gonX** [comment] 2018-08-12 14:24
Applying the attached patch after applying the patchfiles makes WINE compile for me.
[esync-fix.patch.gz](https://github.com/zfigura/wine/files/2281019/esync-fix.patch.gz)

**Comment by tysegall** [comment] 2018-08-12 15:00
@gonX Thanks! I'll try out the patch and see if it works for me. :)  @zfigura any chance you can roll this into your repo so that the patch becomes redundant?

**Comment by zfigura** [comment] 2018-08-12 15:16
I have zero idea how that happened, but I pushed the fix and uploaded a tarball at https://github.com/zfigura/wine/releases/tag/esyncdc9eec7.

**Comment by gonX** [comment] 2018-08-12 17:33
Wine compiles for me with esync dc9eec7 patches applied. Thanks for the quick turnaround!

**Comment by tysegall** [comment] 2018-08-12 17:55
@zfigura That worked. Checked out tag "esyncdc9eec7". Now to get the dxvk libs to be used with it (see this Youtube for my inspiration in trying this: https://www.youtube.com/watch?v=VCtislYGdRs), and I'll kick the tires on it. :)

Thanks again for your help!

**Closed as completed** 2018-08-12 23:00 UTC
